### ISSUE TITLE
Message of ~20kb is too large

### ISSUE THREAD

**Issue by samhh** [neon64/chrome-native-messaging#2]
Hi again!

Here's roughly the code I'm testing with:

```
// In actuality this is a vector, but too much unrelated code to put here
let bookmarks;

// This will succeed
let res = json!({
    "will_i_work": true,
    "one_item": bookmarks.get(1)
});

// This succeeds and confirms that the length of `bookmarks` is 20653
let res = json!({
    "length": serde_json::to_string(&bookmarks)?.len()
});

// This will fail
let res = json!({
    "bookmarks": bookmarks
});

write_output(io::stdout(), &res).unwrap();
```

Assuming `res` is equal to the fail value, the payload sent back to the browser will say this: `Error(MessageTooLarge(20700)`

This falls well short of the 1MB limit as far as I can tell, both in the README and here: https://github.com/neon64/chrome-native-messaging/blob/master/src/lib.rs#L90

Am I missing something? Thanks!

**Comment by neon64** [comment]
Yup just a very silly little bug in my code.. I had written `1024^2`, thinking it would evaluate to 1024 squared, but as its actually the bitwise exclusive or operator, I  enforced (an incorrect) max message length of 1026.

**Comment by neon64** [comment]
This should be fixed in version 0.1.2. Let me know if it isn't.

Also, now that you're sending large messages, would it be useful to have a `write_output` implementation that doesn't go through `serde_json::Value`? (think its slower than raw serde)

**Comment by samhh** [comment]
It is surprising to me coming from other languages that there isn't an exponentiation operator in Rust. 0.1.2 working a charm! 👍 

I'm not sure, Rust is pretty much my first time delving into native/non-web code. Here's what I'm working with at the moment (if you spot any issues, please feel free to point those out!):

```rust
event_loop(|req_json: serde_json::Value| -> Result<(), errors::Error> {
        let req: Result<Request, serde_json::Error> = serde_json::from_value(req_json);

        let res: serde_json::Value = if req.is_ok() {
            let req = req.unwrap();

            match req.method.as_ref() {
                "GET" => {
                    let bookmarks = get_bookmarks(&db_conn);

                    match bookmarks {
                        Ok(bm) => {
                            json!({
                                "success": true,
                                "bookmarks": bm,
                            })
                        }
                        Err(err) => {
                            json!({
                                "success": false,
                                "message": err.description(),
                            })
                        }
                    }
                }
                _ => {
                    json!({
                        "success": false,
                        "message": "Unrecognised request type.",
                    })
                }
            }
        } else {
            json!({
                "success": false,
                "message": "Failed to read incoming JSON.",
            })
        };

        write_output(io::stdout(), &res).unwrap();

        Ok(())
    });
```

**Comment by neon64** [comment]
hmm well if you're wanting the absolute highest performance, then you could consider writing variants of `read_input` and `write_output` which serialize/deserialize straight into a struct which you define, instead of through the intermediate `serde_json::Value` type. Also at the moment the code is blocking, so the extension will have to wait for the DB request to complete before it other messages will be read. However perhaps that's not an issue at the moment.

As far as code style goes, I think you can replace the calls to `unwrap` with the try-operator `?` which will then propagate the error back to the event loop. You also don't need so many type annotations (unless u prefer them), and you could replace:

```
let res: serde_json::Value = if req.is_ok() {
            let req = req.unwrap();
            // do stuff
};
```

with:

```
let res = if let Ok(req) = req {
            // do stuff
}
```

or actually even:

```
let req: Request = serde_json::from_value(req_json)?;
```

which will handle errors and get you access to the underlying `Request` in one go.

I hope that helps.

**Comment by samhh** [comment]
Thanks! Much appreciated. :-)

**Comment by guest271314** [comment]
How did you test the code? 

Is it possible to run Rust from the shebang line?
