### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by colemickens** [neon64/chrome-native-messaging#3]
The [other native messaging library](https://github.com/chrmod/rust-webextension-protocol) seems to be AGPL3. I'm curious if you have plans for licensing for this repo?

Thanks!

**Comment by neon64** [comment]
In the `Cargo.toml` the license is specified to be either MIT or Apache - the same as the Rust project itself (and the default for new cargo projects I think). I've updated the readme to make that more clear

**Comment by colemickens** [comment]
Ah, I think I noted this when I took stock of what was on Crates.io but forgot when I looked for a LICENSE file. Anyway, thanks!
